Web_Lab2.2/Web_Lab2.2/Models/Calc.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web_Lab2._2.Models
{
    public class Calc
    {
        public int a
        {
            get; set;
        }

        public int b
        {
            get; set;
        }

        public string operation
        {
            get; set;
        }
    }
}

Web_Lab2.2/Web_Lab2.2/Controllers/CalcController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Web_Lab2._2.Models;
using Web_Lab2._2.Service;

namespace lab2.Controllers
{
    public class CalcController : Controller
    {
        [Route("Manual")]
        public IActionResult Manual()
        {
            if (HttpContext.Request.Method == "GET")
                return View("WindowInput");

            int a, b;
            string operation;
            if (!int.TryParse(HttpContext.Request.Form["a"], out a))
                return BadRequest();
            if (!int.TryParse(HttpContext.Request.Form["b"], out b))
                return BadRequest();
            operation = HttpContext.Request.Form["operation"];
            if (String.IsNullOrEmpty(operation))
                return BadRequest();

            ViewBag.Result = CalcService.Convert(new Calc { a = a, b = b, operation = operation });
            
            return View("Result");
        }

        [HttpGet]
        [Route("ManualParsingSeparate")]
        public IActionResult ManualParsingSeparate()
        {
            return View("WindowInput");
        }
        [HttpPost]
        [Route("ManualParsingSeparate")]
        public IActionResult ManualParsingSeparateResult()
        {
            int a, b;
            string operation;
            if (!int.TryParse(HttpContext.Request.Form["a"], out a))
                return BadRequest();
            if (!int.TryParse(HttpContext.Request.Form["b"], out b))
                return BadRequest();
            operation = HttpContext.Request.Form["operation"];
            if (String.IsNullOrEmpty(operation))
                return BadRequest();

            ViewBag.Result = CalcService.Convert(new Calc {a = a, b = b, operation = operation});

            return View("Result");
        }

        [Route("ModelBindingParameters")]
        [HttpGet]
        public IActionResult ModelBindingParameters()
        {
            return View("WindowInput");
        }

        [Route("ModelBindingParameters")]
        [HttpPost]
        public IActionResult ModelBindingParametersResult(int a, string operation, int b)
        {
            if (!ModelState.IsValid)
                BadRequest();
            ViewBag.Result = CalcService.Convert(new Calc{ a = a, b = b, operation = operation });

            return View("Result");
        }

        [Route("ModelBindingSeparate")]
        [HttpGet]
        public IActionResult ModelBindingSeparate()
        {
            return View("WindowInput");
        }

        [Route("ModelBindingSeparate")]
        [HttpPost]
        public IActionResult ModelBindingSeparateResult(Calc calc)
        {
            ViewBag.Result = CalcService.Convert(calc);

            return View("Result");
        }
    }
}

Web_Lab2.2/Web_Lab2.2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Web_Lab2._2.Models;

namespace Web_Lab2._2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Web_Lab2.2/Web_Lab2.2/Views/Calc/Result.cshtml
@{ 
    ViewBag.Title = "Result";
}
<h1>Result</h1>
@ViewBag.Result

Web_Lab2.2/Web_Lab2.2/Views/Calc/WindowInput.cshtml
@{ 
    string action ="";

    if (ViewContext.RouteData.Values["Action"] is string)
        action = ViewContext.RouteData.Values["Action"] as string;

    ViewBag.Title = action; }

<h1>@action</h1>

@using (Html.BeginForm(action, "Calc", FormMethod.Post))
{
    @Html.TextBox("a", "", new { type = "number" })
    <br />
    @Html.DropDownList("operation", new SelectList(new[] { "+", "-", "*", "/" }))
    <br />
    @Html.TextBox("b", "", new {type="number" })
    <br />
    <input type="submit" value="Submit" />


}

Web_Lab2.2/Web_Lab2.2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Backend 2";
}

<h1>Form parameters parsing demo</h1>
<ul>
    <li><a asp-controller="Calc" asp-action="Manual">Manual parsing in single action</a></li>
    <li><a asp-controller="Calc" asp-action="ManualParsingSeparate">Manual parsing in separate action</a></li>
    <li><a asp-controller="Calc" asp-action="ModelBindingParameters">Model binding (parameters)</a></li>
    <li><a asp-controller="Calc" asp-action="ModelBindingSeparate">Model binding (separate model)</a></li>
</ul>

Web_Lab2.2/Web_Lab2.2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend 2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Backend 2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Backend 2
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>